import Head from "next/head";
import { Breadcrumb, Layout } from "antd";

const { Content } = Layout;

export default function Home() {
  return (
    // <Head>
    //   <title>Create Next App</title>
    //   <meta name="description" content="Generated by create next app" />
    //   <link rel="icon" href="/favicon.ico" />
    // </Head>
    <Content className="page-home page-wrapper">
      <Breadcrumb>
        <Breadcrumb.Item>Home</Breadcrumb.Item>
      </Breadcrumb>
      <h2 className="page-title">Home</h2>
    </Content>
  );
}
